export const levels = [
	map`
.....1spalewrc.....
...................
...................
...................
...................
...................
...p............e..
..ppp..........eee.
.ppppp........eeeee
ppppppp........eee.
.lpppl..........l..
.lp.pl...t......l..
.lp.pl...b......l..
ddddddddddddddddddd
sssssssssssssssssss`,
]
